services:
  get_your_api_db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: vikas7490
      POSTGRES_PASSWORD: vikas12630
      POSTGRES_DB: my_pg_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  get_your_api_backend:
    build:
      context: ./backend-get-your-api
      dockerfile: Dockerfile
    ports:
      - "1111:1111"
    environment:
      - DATABASE_URL=postgresql://vikas7490:vikas12630@get_your_api_db/my_pg_db
      - RESEND_API_KEY=re_CFxhSKcg_2aKcPVgWxHyoDW7zH1enwMas
    depends_on:
      - get_your_api_db

  get_your_api_frontend:
    build:
      context: ./frontend-get-your-api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - get_your_api_backend
volumes:
  pgdata:
